
all:\
  make_lib_log_time\
  make_lib_log_err\
  make_lib_io_arg

make_lib_log_time:
	$(MAKE) -C lib_log_time

make_lib_log_err:
	$(MAKE) -C lib_log_err

make_lib_io_arg:
	$(MAKE) -C lib_io_arg


clean:\
  clean_lib_log_time\
  clean_lib_log_err\
  clean_lib_io_arg

clean_lib_log_time:
	$(MAKE) -C lib_log_time clean

clean_lib_log_err:
	$(MAKE) -C lib_log_err clean

clean_lib_io_arg:
	$(MAKE) -C lib_io_arg clean

