#
path_report: "out/remap/AMeDAS-1grid_to_3sec/report.txt"

[mesh_latlon]
  nx: 1
  ny: 1
  west: 139.75
  east: 139.7625
  south: 35.511666666667
  north: 35.525
  is_south_to_north: .true.
  in_grid_sz: 2560, 3360
  in_grid_lb: 1741, 1862
  in_grid_ub: 1741, 1862
[end]

[mesh_latlon]
  nx: 11
  ny: 12
  west: 139.7525
  east: 139.761666666667
  south: 35.511666666667
  north: 35.521666666667
  is_south_to_north: .false.
[end]

[remapping]
  dir: "out/remap/AMeDAS-1grid_to_3sec"
  fout_rt_sidx: "grid.bin", int4, 1
  fout_rt_tidx: "grid.bin", int4, 2
  fout_rt_area: "area.bin", dble, 1
  fout_rt_coef: "coef.bin", dble, 1

  mesh_vrf: source
  fout_vrf_grdara_true: "vrf/src_val.bin", rec=1
  fout_vrf_grdara_rt  : "vrf/src_val.bin", rec=2
  fout_vrf_rerr_grdara: "vrf/src_val.bin", rec=3

  mesh_vrf: target
  fout_vrf_grdara_true: "vrf/tgt_val.bin", rec=1
  fout_vrf_grdara_rt  : "vrf/tgt_val.bin", rec=2
  fout_vrf_rerr_grdara: "vrf/tgt_val.bin", rec=3
[end]

[options]
  old_files: remove

  earth_geosys: WGS84
  earth_rtyp: volmetric
[end]
