#
path_report: "out/remap/T85_to_GSWP3/report.txt"

[mesh_latlon]
  name: "T85"
  nx: 256
  ny: 128
  is_south_to_north: .false.
[end]

[mesh_latlon]
  name: "GSWP3"
  nx: 720
  ny: 360
  is_south_to_north: .false.
[end]

[remapping]
  dir: "out/remap/T85_to_GSWP3"
  length_rt: 474336
  fin_rt_sidx: "grid.bin", rec=1
  fin_rt_tidx: "grid.bin", rec=2
  fin_rt_area: "area.bin"
  fin_rt_coef: "coef.bin"

  dir: ""
  fin_grdval: "dat/field/T85/samples/Valcke_gulfstream.bin"
  fout_grdval: "out/remap/in_T85_to_GSWP3/remap/Valcke_gulfstream.bin"
[end]

[options]
  old_files: remove
  earth_geosys: WGS84
  earth_rtyp: ellips
[end]

[figures]
  path_fig  : "out/remap/in_T85_to_GSWP3/fig/src_Valcke_gulstream.png"
  fin_grdval: "dat/field/T85/samples/Valcke_gulfstream.bin"
  mesh: source

  path_fig  : "out/remap/in_T85_to_GSWP3/fig/tgt_Valcke_gulfstream.png"
  fin_grdval: "out/remap/in_T85_to_GSWP3/remap/Valcke_gulfstream.bin"
  mesh: target
[end]
