TOPSRCDIR = ../../..
include $(TOPSRCDIR)/Mkinclude

.SUFFIXES: .f90 .F90 .c
%.o: %.f90
	$(FC) $(FCFLAGS) -c $<\
 -I$(CMNDIR3) -I$(CMNDIR2) -I$(CMNDIR1) -I$(MODDIR)
%.o: %.F90
	$(FC) $(FCFLAGS) $(FOPT_USE_C) $(FOPT_TERMINAL_WIDTH) -c $<\
 -I$(CMNDIR3) -I$(CMNDIR2) -I$(CMNDIR1) -I$(MODDIR)
%.o: %.c
	$(CC) $(CCFLAGS) -c $<\
 -I$(CMNDIR3) -I$(CMNDIR2) -I$(CMNDIR1) -I$(MODDIR)
%.mod: %.f90 %.o
	@:

TARGET = main
BINDIR = $(TOPSRCDIR)/../bin/std
BIN = $(BINDIR)/remap.exe
PY = $(BINDIR)/mkfig_remap.py

OBJ_F = \
	def_type.o\
	mod_set.o\
	mod_remap.o\
	mod_finalize.o\
	main.o

OBJ_ALL = $(OBJ_F)
OBJ_LIB = def_*.o mod_*.o

.PHONY: all
all:
	$(MAKE) $(OBJ_ALL)
	$(MAKE) $(TARGET)

$(TARGET): $(OBJ_ALL) $(CMNDIR3)/*.a $(CMNDIR2)/*.a $(CMNDIR1)/*.a $(LIB)
	$(FC) $(FCFLAGS) -o $@ $^

.PHONY: install
install:
	$(MKDIR) $(MKDIRFLAGS) $(BINDIR)
	$(INSTALL) $(TARGET) $(BIN)
	$(CP) $(CPFLAGS) mkfig.py $(PY)

.PHONY: clean
clean:
	$(RM) $(RMFLAGS) *.o *.mod core *~ *trace temp* $(TARGET)

