
all:\
  make_std\
  make_ext

make_std:
	$(MAKE) -C std

make_ext:
	$(MAKE) -C ext


install:\
  install_std\
  install_ext

install_std:
	$(MAKE) -C std install

install_ext:
	$(MAKE) -C ext install


clean:\
  clean_std\
  clean_ext

clean_std:
	$(MAKE) -C std clean

clean_ext:
	$(MAKE) -C ext clean

