
all:\
  make_1\
  make_2\
  make_3

make_1:
	$(MAKE) -C 1

make_2:
	$(MAKE) -C 2

make_3:
	$(MAKE) -C 3


clean:\
  clean_1\
  clean_2\
  clean_3

clean_1:
	$(MAKE) -C 1 clean

clean_2:
	$(MAKE) -C 2 clean

clean_3:
	$(MAKE) -C 3 clean

